### ISSUE TITLE
Maybe a typo in document?

### ISSUE THREAD

**Issue by Ther-nullptr** [IBM/aihwkit-lightning#9]
![image](https://github.com/user-attachments/assets/15b0622d-ada4-47c4-995d-187438310493)
what is $\lambda_{adc}$ in this equation? I think it is `out_bound` there.

**Comment by jubueche** [comment]
Hi @Ther-nullptr. The Equation is correct. Let me explain. We have the constant `out_bound` which is set globally (let's say `12.0` for 8 bits). You can see from the equation that we clip with $$\beta^{adc quant}$$. This $$\beta^{adc quant}$$ is not the `out_bound`, but a scaled version of it per layer. This is because the layers of the neural networks have different input ranges and different weight ranges. Essentially, $$\beta^{adc quant}$$ is a version of the `out_bound` (which is $$\lambda$$), scaled by the input range ($$\beta^{inp quant}$$) and the weight range ($$max(abs(W))$$). Note that the weight normalization can be done per column (column = output) or per tensor (across all columns).
I hope this clarifies it a bit more. I am closing for now, but feel free to re-open.
